name: Deploy Backend to VPS (Development)

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file for backend
      run: |
        cat > .env << EOF
        # Development Backend Environment Variables
        
        # Firebase Configuration
        FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}
        
        # OpenAI Configuration
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        
        # Server Configuration
        PORT=3001
        NODE_ENV=development
        
        # CORS Configuration
        CORS_ORIGIN=https://dev.ubora-app.com
        EOF
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Create directories if they don't exist
          mkdir -p /var/www/ubora-backend-dev
          cd /var/www/ubora-backend-dev
          
          # Clone repository if it doesn't exist
          if [ ! -d ".git" ]; then
            git clone https://github.com/CamaireTech-Production/Ubora.git .
            git checkout dev
          else
            git pull origin dev
          fi
          
          # Install dependencies
          npm ci
          
          # Create/update .env file
          cat > .env << 'EOF'
          FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          PORT=3001
          NODE_ENV=development
          CORS_ORIGIN=https://dev.ubora-app.com
          EOF
          
          # Stop existing process
          pm2 stop ubora-backend-dev || true
          pm2 delete ubora-backend-dev || true
          
          # Start fresh with PM2
          pm2 start server/production-server.js --name ubora-backend-dev
          pm2 save
          
          # Wait a moment for startup
          sleep 3
          
          # Check if it's running
          pm2 list
          
          # Test the endpoint
          curl -f http://localhost:3001/health || echo "Health check failed"
          
          # Create Nginx configuration for apidev.ubora-app.com
          cat > /etc/nginx/sites-available/apidev.ubora-app.com << 'EOF'
          server {
              listen 80;
              listen 443 ssl;
              server_name apidev.ubora-app.com;
              
              ssl_certificate /etc/letsencrypt/live/apidev.ubora-app.com/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/apidev.ubora-app.com/privkey.pem;
              
              location / {
                  proxy_pass http://localhost:3001;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          EOF
          
          # Enable the site
          ln -sf /etc/nginx/sites-available/apidev.ubora-app.com /etc/nginx/sites-enabled/
          
          # Test and reload Nginx
          nginx -t && systemctl reload nginx
          
          echo "Development backend deployed successfully"
